# Adapted from: https://github.com/errata-ai/vale-action

name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Styles
      run: |
        sudo apt install wget unzip
        wget https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
        unzip Microsoft.zip -d ci/vale/styles/
        wget https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        unzip write-good.zip -d ci/vale/styles/

    - name: Vale
      uses: makeworld-the-better-one/vale-action@v1.4.0
      with:
        files: src
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
